# Generated by Django 5.0.6 on 2024-05-16 16:01

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Book title')),
                ('author', models.CharField(max_length=250, verbose_name='Author')),
                ('book', models.FileField(max_length=250, upload_to=books.models.get_upload_path, verbose_name='Book file')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'unique_together': {('title', 'author')},
            },
        ),
    ]
